### ISSUE TITLE
Ruby Capstone 

### ISSUE THREAD

**Issue by bill7pearl** [bill7pearl/Ruby-kanban#22]
## Link to the kanban board: 
 https://github.com/bill7pearl/Ruby-kanban/projects/1
## Team members:
This is a Ruby capstone project contributed by two partners @bill7pearl & @Salwa99.
## Tasks assigned:
- Team Member # 1: @bill7pearl 
- Team Member # 2: @Salwa99

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- ### Kindly add a description of the following tasks:
   - [ ] https://github.com/bill7pearl/Ruby-kanban/issues/14
   - [ ] https://github.com/bill7pearl/Ruby-kanban/issues/13
   - [ ] https://github.com/bill7pearl/Ruby-kanban/issues/15
   
### as per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.) all tasks should have description.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @bill7pearl and @Salwa99,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
